### ISSUE TITLE
Pillars and Pavers Slaps Directional Facing Options

### ISSUE THREAD

**Issue by LyaVanLou** [TeamMetallurgy/Masonry#26] opened 2022-04-30 15:22 UTC
**Is your feature request related to a problem? Please describe.**
The pillars and pavers have directional facing options, but their slap counterparts don't (see green & red arrows in picture below). 
Which, sure, you can work around it by using the full blocks instead, but you usually went for the slabs for a reason (like preserving resources/space, height variation, etc.)

**Describe the solution you'd like**
Being able to place them in both directions (west-east/south-north) based on placement - facing whatever direction the side of a block you're placing it next to is, or the player's view direction when placing it on the ground/ceiling.

**Describe alternatives you've considered**
Alternative (probably easier to implement) would be added variants of these blocks in these directions, so you'd have "Stone Column Slab" and "Stone Column Slab (90° Rotated)".

**Additional context**
![FeatureRequest](https://user-images.githubusercontent.com/56847157/166111681-21af866a-8d8c-4afa-809b-2b8e5fcf94a0.png)

**Comment by GirafiStudios** [comment] 2024-01-11 18:12
Duplicate of https://github.com/TeamMetallurgy/Masonry/issues/11
Already a planned feature for the future - hopefully :)

**Closed as completed by GirafiStudios** 2024-01-11 18:12 UTC
Labels: Feature
